ticket-back:
  image: pupscan/ticket-back:latest
  container_name: ticket-back
  restart: unless-stopped
  ports:
    - 8080:8080
  environment:
    - ZEN_DESK_AUTHORIZATION=AUTHORIZATION_HEADER_CODE
  links:
    - mongo:mongo

mongo:
  image: mongo:latest
  container_name: ticket-mongodb
  volumes:
    - ./data/mongo:/data/db
    - /etc/localtime:/etc/localtime:ro