#front:
#  image: pupscan/ticket-front
#  container_name: ticket-front
#  ports:
#      - 8080:8080
#  links:
#      - ticket:ticket

#ticket:
#  image: pupscan/ticket-back
#  container_name: ticket-back
#  links:
#      - mongo:mongo

mongo:
   image: mongo:latest
   container_name: mongo
   volumes:
     - ./data/mongo:/data/db
   ports:
     - 27017:27017